#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

"""
Generate a LaTeX table of publish_date ranges per fold for the two primary
temporal CV strategies: temporal LOO Block CV and temporal GW CV.

Only test and holdout phases are present in index_results.parquet (training
samples are not stored there), so the table shows test-set date ranges only.

Usage:
    uv run scripts/extract_fold_date_ranges.py
    uv run scripts/extract_fold_date_ranges.py --output-dir data/eda
"""
from __future__ import annotations

import sys
from argparse import ArgumentParser
from pathlib import Path

import polars as pl

try:
    from scripts import EDA_DIR, INDEX_RESULTS_FILE
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from scripts import EDA_DIR, INDEX_RESULTS_FILE

LOO_TYPE = "temporal_loo_block_cross_validation"
GW_TYPE = "temporal_growing_window_cross_validation"

LOO_LABEL = "Temporal LOO Block CV"
GW_LABEL = "Temporal GW CV"


def _fmt(ranges: dict, fold_type: str, fold_num: int, phase: str) -> str:
    key = (fold_type, fold_num, phase)
    if key not in ranges:
        return r"\textemdash"
    s, e = ranges[key]
    return f"{s}\\,--\\,{e}"


def _table_body(ranges: dict, fold_nums: list[int]) -> list[str]:
    lines: list[str] = [
        "    \\toprule",
        f"    Fold & \\textit{{{LOO_LABEL}}} & \\textit{{{GW_LABEL}}} \\\\",
        "    \\midrule",
    ]
    for fn in fold_nums:
        loo = _fmt(ranges, LOO_TYPE, fn, "test")
        gw = _fmt(ranges, GW_TYPE, fn, "test")
        lines.append(f"    {fn} & {loo} & {gw} \\\\")
    lines.append("    \\midrule")
    loo_h = _fmt(ranges, LOO_TYPE, 0, "holdout")
    gw_h = _fmt(ranges, GW_TYPE, 0, "holdout")
    lines.append(f"    Holdout & {loo_h} & {gw_h} \\\\")
    lines.append("    \\bottomrule")
    return lines


def build_latex(ranges: dict, fold_nums: list[int]) -> str:
    lines: list[str] = [
        "% Auto-generated by scripts/extract_fold_date_ranges.py — do not edit manually.",
        "% Requires: \\usepackage{booktabs}",
        "\\begin{table}[ht]",
        "  \\centering",
        "  \\footnotesize",
        "  \\begin{tabular}{l cc}",
    ]
    lines += _table_body(ranges, fold_nums)
    lines += [
        "  \\end{tabular}",
        "  \\caption{Test-set date ranges (year-month) for each fold under two temporal"
        " cross-validation strategies."
        " The holdout set is fixed and identical across all folds.}",
        "  \\label{tab:fold_date_ranges}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def build_latex_rotated(ranges: dict, fold_nums: list[int]) -> str:
    lines: list[str] = [
        "% Auto-generated by scripts/extract_fold_date_ranges.py — do not edit manually.",
        "% Requires: \\usepackage{booktabs}, \\usepackage{rotating}",
        "\\begin{sidewaystable}[ht]",
        "  \\centering",
        "  \\scriptsize",
        "  \\renewcommand{\\arraystretch}{0.85}\\setlength{\\tabcolsep}{4pt}",
        "  \\begin{tabular}{l cc}",
    ]
    lines += _table_body(ranges, fold_nums)
    lines += [
        "  \\end{tabular}",
        "  \\caption{Test-set date ranges (year-month) for each fold under two temporal"
        " cross-validation strategies (rotated)."
        " The holdout set is fixed and identical across all folds.}",
        "  \\label{tab:fold_date_ranges_rotated}",
        "\\end{sidewaystable}",
    ]
    return "\n".join(lines) + "\n"


def build_latex_transposed(ranges: dict, fold_nums: list[int]) -> str:
    n_cols = len(fold_nums) + 1  # folds + holdout
    col_spec = "l" + "c" * n_cols
    lines = [
        "% Auto-generated by scripts/extract_fold_date_ranges.py — do not edit manually.",
        "% Requires: \\usepackage{booktabs}, \\usepackage{graphicx}",
        "\\begin{table}[ht]",
        "  \\centering",
        "  \\footnotesize",
        "  \\setlength{\\tabcolsep}{4pt}",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
    ]
    header_cells = [""] + [f"\\rotatebox{{90}}{{{fn}}}" for fn in fold_nums] + ["\\rotatebox{90}{Holdout}"]
    lines.append("    " + " & ".join(header_cells) + " \\\\")
    lines.append("    \\midrule")
    for fold_type, label in [(LOO_TYPE, LOO_LABEL), (GW_TYPE, GW_LABEL)]:
        cells = [f"\\textit{{{label}}}"]
        for fn in fold_nums:
            cells.append(f"\\rotatebox{{90}}{{{_fmt(ranges, fold_type, fn, 'test')}}}")
        cells.append(f"\\rotatebox{{90}}{{{_fmt(ranges, fold_type, 0, 'holdout')}}}")
        lines.append("    " + " & ".join(cells) + " \\\\")
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        "  \\caption{Test-set date ranges (year-month) per fold for two temporal"
        " cross-validation strategies. The holdout set is fixed and identical across all folds.}",
        "  \\label{tab:fold_date_ranges}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    p = ArgumentParser(description=__doc__)
    p.add_argument("--output-dir", type=Path, default=EDA_DIR)
    args = p.parse_args()

    print(f"Loading {INDEX_RESULTS_FILE} …")
    schema = pl.read_parquet_schema(INDEX_RESULTS_FILE)
    needed = [c for c in ["fold_type", "fold_number", "phase", "publish_date"] if c in schema]

    lf = (
        pl.scan_parquet(INDEX_RESULTS_FILE)
        .select(needed)
        .filter(pl.col("fold_type").is_in([LOO_TYPE, GW_TYPE]))
    )

    try:
        agg = (
            lf.group_by(["fold_type", "fold_number", "phase"])
            .agg(
                pl.col("publish_date").min().alias("start"),
                pl.col("publish_date").max().alias("end"),
            )
            .collect(engine="streaming")
        )
    except Exception:
        agg = (
            lf.group_by(["fold_type", "fold_number", "phase"])
            .agg(
                pl.col("publish_date").min().alias("start"),
                pl.col("publish_date").max().alias("end"),
            )
            .collect()
        )

    if agg.is_empty():
        print("ERROR: no rows matched — check that index_results.parquet contains the two fold types.")
        sys.exit(1)

    ranges: dict[tuple[str, int, str], tuple[str, str]] = {
        (r["fold_type"], r["fold_number"], r["phase"]): (r["start"][:7], r["end"][:7])
        for r in agg.iter_rows(named=True)
        if r["start"] and r["end"]
    }

    fold_nums = sorted(
        agg.filter(pl.col("phase") == "test")["fold_number"].unique().to_list()
    )
    print(f"Found {len(fold_nums)} fold(s): {fold_nums}")

    for (ft, fn, phase), (s, e) in sorted(ranges.items()):
        print(f"  {ft} | fold {fn:2d} | {phase:8s}: {s} – {e}")

    out_dir = args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    out_path = out_dir / "fold_date_ranges.tex"
    out_path.write_text(build_latex_transposed(ranges, fold_nums))
    print(f"\nSaved → {out_path}")

    out_portrait = out_dir / "fold_date_ranges_portrait.tex"
    out_portrait.write_text(build_latex(ranges, fold_nums))
    print(f"Saved → {out_portrait}")


if __name__ == "__main__":
    main()
