#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

"""
P-value comparison heatmaps across fold types for each model.

Produces per-model p-value heatmaps (one subplot per model) plus a summary
subplot showing the average p-value across all models.  Both paired t-test and
Wilcoxon signed-rank results are written as separate figures.

Outputs to data/plots/6_pvalue_comparison/.

Usage:
    uv run scripts/plot_pvalue_summary.py
    uv run scripts/plot_pvalue_summary.py --metric f1 --phase test
    uv run scripts/plot_pvalue_summary.py --tag fine-tuning --dataset megavul
"""
from __future__ import annotations

import math
import sys
import warnings
from argparse import ArgumentParser
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import polars as pl
import seaborn as sns
from scipy.stats import t as t_dist
from statsmodels.stats.multitest import multipletests

try:
    from scripts import INDEX_RESULTS_FILE
    from scripts.plot_results import METRICS, load_results
    from scripts.plot_statistical_tests import (
        MIN_PAIRED_FOLDS,
        _build_symmetric_matrix,
        prepare_per_fold_metrics,
        run_pairwise_tests,
    )
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from scripts import INDEX_RESULTS_FILE
    from scripts.plot_results import METRICS, load_results
    from scripts.plot_statistical_tests import (
        MIN_PAIRED_FOLDS,
        _build_symmetric_matrix,
        prepare_per_fold_metrics,
        run_pairwise_tests,
    )

# ─── Constants ────────────────────────────────────────────────────────────────

PLOTS_DIR = Path(__file__).resolve().parents[1] / "data" / "plots" / "6_pvalue_comparison"

PHASES = ["test", "holdout"]

_VMAX = 1.0  # p-value colorscale ceiling (0-1 range)
_CMAP = "RdYlGn"

# TOST equivalence testing constants
TOST_DELTA = 2.0   # equivalence margin in pp F1
TOST_ALPHA = 0.05

# Each tuple: (random fold short name, temporal fold short name)
# Short names map to fold type prefixes via _FOLD_SHORT_TO_PREFIX
_FOLD_SHORT_TO_PREFIX = {
    "K-Fold":   "K-Fold CV",
    "Rand LOO": "Random LOO Block CV",
    "Rand GW":  "Random Growing Window CV",
    "Temp LOO": "Temporal LOO Block CV",
    "Temp GW":  "Temporal Growing Window CV",
}

TOST_PAIRS = [
    ("K-Fold",   "Temp LOO"),
    ("K-Fold",   "Temp GW"),
    ("Rand LOO", "Temp LOO"),
    ("Rand GW",  "Temp GW"),
    ("K-Fold",   "Rand LOO"),
]

RANDOM_PAIRS = [
    ("K-Fold",   "Rand LOO"),
    ("K-Fold",   "Rand GW"),
    ("Rand LOO", "Rand GW"),
]

TEMPORAL_PAIRS = [
    ("Temp LOO", "Temp GW"),
]

CROSS_PAIRS = [
    ("K-Fold",   "Temp LOO"),
    ("Rand LOO", "Temp LOO"),
    ("Rand GW",  "Temp GW"),
]

def _abbreviate_fold_type(ft: str) -> str:
    """Abbreviate fold type name for heatmap display."""
    if ft.startswith("K-Fold"):
        return "K-Fold"
    elif ft.startswith("Random Growing Window"):
        return "R-GW"
    elif ft.startswith("Random LOO Block"):
        return "R-LOO-B"
    elif ft.startswith("Temporal Growing Window"):
        return "T-GW"
    elif ft.startswith("Temporal LOO Block"):
        return "T-LOO-B"
    else:
        return ft


def _pvalue_colour(p: float) -> str:
    """Interpolate white→red for p-value: white (p=1) to red (p=0)."""
    t = 1.0 - p  # 0 at p=1, 1 at p=0
    r = int(round(255 - t * (255 - 229)))  # 255 → 229 (red channel)
    g = int(round(255 - t * (255 - 87)))   # 255 → 87  (green channel)
    b = int(round(255 - t * (255 - 87)))   # 255 → 87  (blue channel)
    return f"{r:02X}{g:02X}{b:02X}"


def _pvalue_cell(p: float) -> str:
    """Return a coloured cell string: \\cellcolor[HTML]{hex} p-value."""
    if np.isnan(p):
        return "\\cellcolor[HTML]{FFFFFF} ---"
    colour = _pvalue_colour(p)
    return f"\\cellcolor[HTML]{{{colour}}} {p:.3f}"


def _build_pvalue_latex_table(
    mat: "pd.DataFrame",
    fold_types: list[str],
    phase: str,
) -> str:
    """Build a lower-triangular p-value LaTeX table."""
    n_ft = len(fold_types)

    def _short_abbrev(ft: str) -> str:
        return _abbreviate_fold_type(ft)

    col_spec = f"l *{{{n_ft}}}{{c}}"

    lines: list[str] = [
        "% Auto-generated by scripts/plot_pvalue_summary.py - do not edit manually.",
        "% Requires: \\usepackage{booktabs}, \\usepackage{colortbl}, \\usepackage{xcolor}",
        "\\begin{table}[ht]",
        "  \\centering",
        "  \\footnotesize",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
        f"    Fold Type & {' & '.join(f'\\rotatebox{{60}}{{\\footnotesize {_short_abbrev(ft)}}}' for ft in fold_types)} \\\\",
        "    \\midrule",
    ]

    for i, row_ft in enumerate(fold_types):
        row_label = _short_abbrev(row_ft)
        cells = [f"\\texttt{{{row_label}}}"]
        for j, col_ft in enumerate(fold_types):
            if i < j:
                cells.append("\\cellcolor[HTML]{F5F5F5} ---")
            else:
                val = mat.at[row_ft, col_ft] if (row_ft in mat.index and col_ft in mat.columns) else float("nan")
                cells.append(_pvalue_cell(val))
        lines.append(f"    {' & '.join(cells)} \\\\")

    lines.append("    \\bottomrule")
    lines.append("  \\end{tabular}")
    lines.append(
        "  \\caption{P-values from paired t-tests comparing fold-type performance on the"
        f" \\textbf{{{phase}}} set, fine-tuned models."
        " White (p=1, not significant) $\\to$ red (p≈0, highly significant).}"
    )
    lines.append(f"  \\label{{tab:pvalue_summary_{phase}}}")
    lines.append("\\end{table}")
    return "\n".join(lines) + "\n"


# ─── TOST helpers ────────────────────────────────────────────────────────────


def _fmt_pvalue(p: float) -> str:
    """Format p-value: '< 0.001' for very small values, 3 decimal places otherwise."""
    if p < 0.001:
        return "< 0.001"
    return f"{p:.3f}"


def _resolve_fold_type(short: str, available: list[str]) -> str | None:
    """Return the first available fold type that starts with the prefix for `short`."""
    prefix = _FOLD_SHORT_TO_PREFIX.get(short, short)
    for ft in available:
        if ft.startswith(prefix):
            return ft
    return None


def paired_tost(
    scores_a: np.ndarray,
    scores_b: np.ndarray,
    delta: float = TOST_DELTA,
    alpha: float = TOST_ALPHA,
) -> tuple[float, float, float, float, float, float]:
    """Paired TOST (Two One-Sided Tests).

    Returns (mean_d, ci_lo, ci_hi, p_lower, p_upper, p_tost).
    90% CI is correct for TOST at α=0.05 (each one-sided test at α=0.05).
    """
    d = scores_a - scores_b
    n = len(d)
    mean_d = float(np.mean(d))
    se = float(np.std(d, ddof=1) / np.sqrt(n))
    df = n - 1

    if se < 1e-12:
        # Zero variance: differences are identical, trivially equivalent
        ci_lo = mean_d
        ci_hi = mean_d
        p_lower = 0.0
        p_upper = 0.0
        p_tost = 0.0
        return mean_d, ci_lo, ci_hi, p_lower, p_upper, p_tost

    t_lower = (mean_d + delta) / se   # H0: mu <= -delta
    t_upper = (mean_d - delta) / se   # H0: mu >= +delta

    p_lower = float(1.0 - t_dist.cdf(t_lower, df))
    p_upper = float(t_dist.cdf(t_upper, df))
    p_tost = max(p_lower, p_upper)

    quantile = float(t_dist.ppf(1.0 - alpha, df))
    ci_lo = mean_d - quantile * se
    ci_hi = mean_d + quantile * se

    return mean_d, ci_lo, ci_hi, p_lower, p_upper, p_tost


def extract_mean_f1_matrix(
    metrics_df: pl.DataFrame,
    metric: str = "f1",
) -> dict[str, dict[str, float]]:
    """Return {model: {fold_type: mean_f1}} averaged across fold numbers."""
    result: dict[str, dict[str, float]] = {}
    for model in metrics_df["model"].unique().to_list():
        model_df = metrics_df.filter(pl.col("model") == model)
        result[model] = {}
        for ft in model_df["fold_type"].unique().to_list():
            vals = model_df.filter(pl.col("fold_type") == ft)[metric].to_numpy().astype(float)
            if len(vals) > 0:
                result[model][ft] = float(np.mean(vals))
    return result


# ─── Superiority test helpers ────────────────────────────────────────────────


def run_superiority_pairs(
    test_f1: dict[str, dict[str, float]],
    models: list[str],
) -> list[dict]:
    """One-sided paired t-test (H1: random > temporal) for each TOST_PAIR.

    Returns list of dicts with keys:
        label, short_a, short_b, n, mean_d, ci_lo, ci_hi,
        t_stat, p_one_sided, p_corrected, significant, direction
    """
    available_fold_types = list({ft for m in models for ft in test_f1.get(m, {})})

    rows: list[dict] = []
    for short_a, short_b in TOST_PAIRS:
        ft_a = _resolve_fold_type(short_a, available_fold_types)
        ft_b = _resolve_fold_type(short_b, available_fold_types)
        if ft_a is None or ft_b is None:
            print(f"  Superiority: skipping pair ({short_a}, {short_b}) - fold type not found")
            continue

        scores_a, scores_b = [], []
        for m in models:
            fa = test_f1.get(m, {}).get(ft_a)
            fb = test_f1.get(m, {}).get(ft_b)
            if fa is not None and fb is not None:
                scores_a.append(fa)
                scores_b.append(fb)

        if len(scores_a) < 2:
            print(f"  Superiority: skipping pair ({short_a}, {short_b}) - fewer than 2 observations")
            continue

        a = np.array(scores_a) * 100.0   # convert to pp
        b = np.array(scores_b) * 100.0
        d = a - b
        n = len(d)
        mean_d = float(np.mean(d))
        se = float(np.std(d, ddof=1) / np.sqrt(n))
        df = n - 1

        if se < 1e-12:
            t_stat = 0.0
            p_one_sided = 0.5
            ci_lo = mean_d
            ci_hi = mean_d
        else:
            t_stat = float(mean_d / se)
            p_one_sided = float(1.0 - t_dist.cdf(t_stat, df))   # upper-tail: H1 random > temporal
            q95 = float(t_dist.ppf(0.975, df))                   # 95% two-sided CI
            ci_lo = mean_d - q95 * se
            ci_hi = mean_d + q95 * se

        rows.append({
            "label":       f"{short_a} vs {short_b}",
            "short_a":     short_a,
            "short_b":     short_b,
            "ft_a":        ft_a,
            "ft_b":        ft_b,
            "n":           n,
            "mean_d":      mean_d,
            "ci_lo":       ci_lo,
            "ci_hi":       ci_hi,
            "t_stat":      t_stat,
            "p_one_sided": p_one_sided,
        })

    if not rows:
        return rows

    p_values = [r["p_one_sided"] for r in rows]
    reject, p_corrected, _, _ = multipletests(p_values, alpha=TOST_ALPHA, method="holm")
    for i, row in enumerate(rows):
        row["p_corrected"] = float(p_corrected[i])
        row["significant"] = bool(p_corrected[i] < TOST_ALPHA)
        row["direction"] = "random > temporal" if row["mean_d"] > 0 else "random ≤ temporal"

    return rows


def plot_superiority_forest(
    sup_results: list[dict],
    family_label: str,
    metric: str = "f1",
) -> Path | None:
    """Forest plot for one-sided superiority test (test-set F1 differences)."""
    if not sup_results:
        return None

    labels = [r["label"] for r in sup_results]
    means  = [r["mean_d"]  for r in sup_results]
    lo     = [r["ci_lo"]   for r in sup_results]
    hi     = [r["ci_hi"]   for r in sup_results]
    sig    = [r["significant"] for r in sup_results]

    n = len(labels)
    y_pos = list(range(n))

    fig, ax = plt.subplots(figsize=(8, max(3, n * 1.1 + 1.5)))

    for i, (mean, lo_i, hi_i, is_sig) in enumerate(zip(means, lo, hi, sig)):
        color = "#2166ac" if is_sig else "#d6604d"
        ax.errorbar(
            mean, i,
            xerr=[[mean - lo_i], [hi_i - mean]],
            fmt="o",
            color=color,
            ecolor=color,
            capsize=5,
            markersize=8,
            linewidth=2,
        )

    ax.axvline(0, color="black", linestyle="--", linewidth=1.2, label="No effect (0 pp)")

    from matplotlib.lines import Line2D
    legend_handles = [
        Line2D([0], [0], marker="o", color="w", markerfacecolor="#2166ac", markersize=9,
               label="Significant (random > temporal, Holm–Bonferroni)"),
        Line2D([0], [0], marker="o", color="w", markerfacecolor="#d6604d", markersize=9,
               label="Not significant"),
        Line2D([0], [0], color="black", linestyle="--", label="No effect (0 pp)"),
    ]
    ax.legend(handles=legend_handles, loc="lower right", fontsize=9)

    ax.set_yticks(y_pos)
    ax.set_yticklabels(labels, fontsize=11)
    ax.set_xlabel("Mean test F1 difference (random − temporal, pp)", fontsize=11)
    ax.set_title(
        f"Superiority Test - Test F1 (H₁: random > temporal, Holm–Bonferroni)",
        fontsize=12,
        fontweight="bold",
    )
    ax.grid(axis="x", alpha=0.3)
    plt.tight_layout()

    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = PLOTS_DIR / f"superiority_forest_{family_label}.png"
    fig.savefig(out_path, dpi=600, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")
    return out_path


def write_superiority_latex_table(
    sup_results: list[dict],
    family_label: str,
) -> Path:
    """Write a LaTeX table of one-sided superiority test results."""
    lines = [
        "% Auto-generated by scripts/plot_pvalue_summary.py - do not edit manually.",
        "% Requires: \\usepackage{booktabs}",
        "\\begin{table}[ht]",
        "  \\centering",
        "  \\footnotesize",
        "  \\begin{tabular}{lrrrrl}",
        "    \\toprule",
        "    Comparison & $\\bar{d}$ (pp) & 95\\% CI & $t$ & $p$ (one-sided, corr.) & Sig. \\\\",
        "    \\midrule",
    ]

    for r in sup_results:
        ci_str = f"[{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}]"
        sig_str = "Yes" if r["significant"] else "No"
        lines.append(
            f"    {r['label']} & {r['mean_d']:+.2f} & {ci_str} & "
            f"{r['t_stat']:+.2f} & {_fmt_pvalue(r['p_corrected'])} & {sig_str} \\\\"
        )

    family_display = "Fine-tuned (LoRA)" if family_label == "finetuned" else "Zero-shot (GGUF)"
    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        f"  \\caption{{One-sided superiority test on \\textbf{{test}}-set F1 ({family_display}). "
        f"$\\bar{{d}}$: mean difference (random~$-$~temporal, pp). "
        f"95\\% two-sided CI. $p$: Holm--Bonferroni corrected one-sided $p$-value. "
        f"Sig.: $p < {TOST_ALPHA}$ (H$_1$: random $>$ temporal).}}",
        f"  \\label{{tab:superiority_{family_label}}}",
        "\\end{table}",
    ]

    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = PLOTS_DIR / f"superiority_table_{family_label}.tex"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"  Saved: {out_path}")
    return out_path


# ─── Intra-group comparison ──────────────────────────────────────────────────


def run_intragroup_pairs(
    test_f1: dict[str, dict[str, float]],
    models: list[str],
    pairs: list[tuple[str, str]],
) -> list[dict]:
    """Two-sided paired t-test + TOST for within-group fold-type pairs (cross-model).

    Each observation is one model's mean F1 for that fold type.
    Returns list of dicts with keys:
        label, short_a, short_b, n, mean_d, ci_lo, ci_hi,
        t_stat, p_two_sided, p_corrected, significant,
        p_tost, equivalent
    """
    available_fold_types = list({ft for m in models for ft in test_f1.get(m, {})})

    rows: list[dict] = []
    for short_a, short_b in pairs:
        ft_a = _resolve_fold_type(short_a, available_fold_types)
        ft_b = _resolve_fold_type(short_b, available_fold_types)
        if ft_a is None or ft_b is None:
            print(f"  Intra-group: skipping pair ({short_a}, {short_b}) - fold type not found")
            continue

        scores_a, scores_b = [], []
        for m in models:
            fa = test_f1.get(m, {}).get(ft_a)
            fb = test_f1.get(m, {}).get(ft_b)
            if fa is not None and fb is not None:
                scores_a.append(fa)
                scores_b.append(fb)

        if len(scores_a) < 2:
            print(f"  Intra-group: skipping pair ({short_a}, {short_b}) - fewer than 2 observations")
            continue

        a = np.array(scores_a) * 100.0
        b = np.array(scores_b) * 100.0
        n = len(a)

        # Two-sided paired t-test (95% CI)
        d = a - b
        mean_d = float(np.mean(d))
        se = float(np.std(d, ddof=1) / np.sqrt(n))
        df = n - 1
        if se < 1e-12:
            t_stat = 0.0
            p_two_sided = 1.0
            ci_lo_95 = mean_d
            ci_hi_95 = mean_d
        else:
            t_stat = float(mean_d / se)
            p_two_sided = float(2.0 * t_dist.cdf(-abs(t_stat), df))
            q975 = float(t_dist.ppf(0.975, df))
            ci_lo_95 = mean_d - q975 * se
            ci_hi_95 = mean_d + q975 * se

        # TOST (90% CI, α=0.05)
        tost_mean_d, ci_lo_90, ci_hi_90, p_lower, p_upper, p_tost = paired_tost(a, b)

        rows.append({
            "label":        f"{short_a} vs {short_b}",
            "short_a":      short_a,
            "short_b":      short_b,
            "ft_a":         ft_a,
            "ft_b":         ft_b,
            "n":            n,
            "mean_d":       mean_d,
            "ci_lo":        ci_lo_90,
            "ci_hi":        ci_hi_90,
            "t_stat":       t_stat,
            "p_two_sided":  p_two_sided,
            "p_tost":       p_tost,
            "equivalent":   bool(p_tost < TOST_ALPHA),
        })

    if not rows:
        return rows

    p_values = [r["p_two_sided"] for r in rows]
    reject, p_corrected, _, _ = multipletests(p_values, alpha=TOST_ALPHA, method="holm")
    for i, row in enumerate(rows):
        row["p_corrected"] = float(p_corrected[i])
        row["significant"] = bool(p_corrected[i] < TOST_ALPHA)

    return rows


def write_intragroup_latex_table(
    random_results: list[dict],
    temporal_results: list[dict],
    family_label: str,
) -> Path:
    """Write a LaTeX table of within-group TOST + two-sided t-test results."""
    family_display = "Fine-tuned (LoRA)" if family_label == "finetuned" else "Zero-shot (GGUF)"
    ncols = 7

    lines = [
        "% Auto-generated by scripts/plot_pvalue_summary.py - do not edit manually.",
        "% Requires: \\usepackage{booktabs}",
        "\\begin{table}[ht]",
        "  \\centering",
        "  \\small",
        "  \\begin{tabular}{lrrrrlrl}",
        "    \\toprule",
        "    Comparison & $\\bar{d}$ (pp) & 90\\% CI & $p_{\\text{TOST}}$ & Equiv. & $p_{\\text{diff}}$ & Sig.\\,diff \\\\",
        "    \\midrule",
    ]

    for r in random_results:
        ci_str = f"[{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}]"
        equiv_str = "Yes" if r["equivalent"] else "No"
        sig_str = "Yes" if r["significant"] else "No"
        lines.append(
            f"    {r['label']} & {r['mean_d']:+.2f} & {ci_str} & "
            f"{_fmt_pvalue(r['p_tost'])} & {equiv_str} & "
            f"{_fmt_pvalue(r['p_corrected'])} & {sig_str} \\\\"
        )

    for r in temporal_results:
        ci_str = f"[{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}]"
        equiv_str = "Yes" if r["equivalent"] else "No"
        sig_str = "Yes" if r["significant"] else "No"
        lines.append(
            f"    {r['label']} & {r['mean_d']:+.2f} & {ci_str} & "
            f"{_fmt_pvalue(r['p_tost'])} & {equiv_str} & "
            f"{_fmt_pvalue(r['p_corrected'])} & {sig_str} \\\\"
        )

    lines += [
        "    \\bottomrule",
        "  \\end{tabular}",
        f"  \\caption{{Within-group TOST equivalence and two-sided paired $t$-tests on \\textbf{{test}}-set F1 ({family_display}), aggregated across models. "
        f"$\\bar{{d}}$: mean difference (A~$-$~B, pp); 90\\% CI corresponds to $\\alpha={TOST_ALPHA}$ TOST. "
        f"Equiv.: $p_{{\\text{{TOST}}}} < {TOST_ALPHA}$, $\\Delta = {TOST_DELTA}$\\,pp. "
        f"$p_{{\\text{{diff}}}}$: Holm--Bonferroni corrected two-sided $p$-value (Sig.\\,diff: $p < {TOST_ALPHA}$).}}",
        f"  \\label{{tab:intragroup_{family_label}}}",
        "\\end{table}",
    ]

    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = PLOTS_DIR / f"intragroup_table_{family_label}.tex"
    out_path.write_text("\n".join(lines) + "\n")
    print(f"  Saved: {out_path}")
    return out_path


# ─── Helpers ─────────────────────────────────────────────────────────────────


def _grid_shape(n: int) -> tuple[int, int]:
    """Return (nrows, ncols) for a roughly-square grid of n panels."""
    ncols = math.ceil(math.sqrt(n))
    nrows = math.ceil(n / ncols)
    return nrows, ncols


def _heatmap_panel(
    ax: plt.Axes,
    matrix: "pd.DataFrame",
    title: str,
    annot: bool = True,
) -> None:
    """Draw a single p-value heatmap on ax."""
    mask = np.isnan(matrix.values)
    sns.heatmap(
        matrix,
        ax=ax,
        mask=mask,
        annot=annot,
        fmt=".3f",
        cmap=_CMAP,
        vmin=0.0,
        vmax=_VMAX,
        linewidths=0.4,
        linecolor="white",
        cbar=True,
        cbar_kws={"shrink": 0.4},
        annot_kws={"size": 15},
    )
    ax.set_aspect(0.5, adjustable='box')
    ax.set_title(title, fontsize=14, fontweight="bold", pad=4)
    ax.tick_params(axis="both", labelsize=12)
    # Abbreviate tick labels for display
    abbrev_x_labels = [_abbreviate_fold_type(label.get_text()) for label in ax.get_xticklabels()]
    abbrev_y_labels = [_abbreviate_fold_type(label.get_text()) for label in ax.get_yticklabels()]
    ax.set_xticklabels(abbrev_x_labels, rotation=0)
    ax.set_yticklabels(abbrev_y_labels, rotation=0)
    ax.set_xlabel("")
    ax.set_ylabel("")


# ─── Main plot function ───────────────────────────────────────────────────────


def plot_pvalue_summary(
    metrics_df: pl.DataFrame,
    phase: str,
    metric: str,
    test_col: str,
    col_label: str,
) -> "pd.DataFrame | None":
    """
    Build a grid of per-model p-value heatmaps plus a summary (average) heatmap.

    Returns the fine-tuned summary matrix for LaTeX table generation (ttest only).

    Args:
        metrics_df: Per-fold metric DataFrame (output of prepare_per_fold_metrics).
        phase:      "test" or "holdout".
        metric:     Metric name (e.g. "f1").
        test_col:   Column in run_pairwise_tests output ("P-Value" or "Wilcoxon P-Value").
        col_label:  Short label used in file name and titles ("ttest" or "wilcoxon").
    """
    models = sorted(metrics_df["model"].unique().to_list())
    if not models:
        return None

    # Union of all fold types across all models - restrict to the 5 primary CV strategies
    _PRIMARY_PREFIXES = (
        "K-Fold CV",
        "Random Growing Window CV",
        "Random LOO Block CV",
        "Temporal Growing Window CV",
        "Temporal LOO Block CV",
    )
    all_fold_types = sorted(
        ft for ft in metrics_df["fold_type"].unique().to_list()
        if any(ft.startswith(p) for p in _PRIMARY_PREFIXES)
    )
    n_ft = len(all_fold_types)
    if n_ft < 2:
        print(f"  [{col_label}] Need ≥2 fold types; skipping.")
        return None

    # Collect per-model p-value matrices
    model_matrices: dict[str, "pd.DataFrame"] = {}
    for model in models:
        results = run_pairwise_tests(metrics_df, model, metric=metric)
        if results.empty:
            continue
        # ttest_rel / wilcoxon return NaN when all pairwise differences are zero
        # (zero-variance case: model performed identically across every fold).
        # Semantically this is "not significant" (p=1.0), so fill NaN → 1.0 to
        # distinguish "tested, identical" from "never tested" (left as NaN).
        results = results.copy()
        results[test_col] = results[test_col].fillna(1.0)
        mat = _build_symmetric_matrix(results, all_fold_types, test_col, diag_val=float("nan"))
        for ft in all_fold_types:
            mat.at[ft, ft] = 1.0  # trivial diagonal: comparing a fold type with itself
        model_matrices[model] = mat

    valid_models = list(model_matrices.keys())
    if not valid_models:
        print(f"  [{col_label}] No valid model pairs; skipping.")
        return None

    # Summary: nanmean across all model matrices
    stacked = np.stack([model_matrices[m].values for m in valid_models], axis=0)
    # Diagonal values are 1.0 (trivial) - replace with NaN before averaging so
    # diagonal is excluded from the summary mean and rendered as NaN (white).
    diag_mask = np.eye(n_ft, dtype=bool)
    stacked[:, diag_mask] = np.nan
    summary_values = np.nanmean(stacked, axis=0)
    # Restore diagonal = 1.0 for visual consistency
    np.fill_diagonal(summary_values, 1.0)

    import pandas as pd
    summary_mat = pd.DataFrame(summary_values, index=all_fold_types, columns=all_fold_types)

    # ── Figure layout ─────────────────────────────────────────────────────────
    n_panels = len(valid_models) + 1  # +1 for summary
    nrows, ncols = _grid_shape(n_panels)

    cell_size = max(2.8, n_ft * 0.7)
    subplot_size = cell_size * n_ft * 0.4 + 2.5
    fig, axes = plt.subplots(
        nrows, ncols,
        figsize=(ncols * subplot_size, nrows * subplot_size),
        squeeze=False,
    )

    test_label = "Paired T-test" if col_label == "ttest" else "Wilcoxon Signed-Rank"
    fig.suptitle(
        f"P-Value Comparison by Fold Type - {test_label} ({metric.upper()}, {phase})",
        fontsize=18,
        fontweight="bold",
        y=0.995,
    )

    # Per-model heatmaps
    for idx, model in enumerate(valid_models):
        row, col = divmod(idx, ncols)
        ax = axes[row][col]
        _heatmap_panel(ax, model_matrices[model], title=model)

    # Summary heatmap (last occupied cell)
    sum_idx = len(valid_models)
    sum_row, sum_col = divmod(sum_idx, ncols)
    _heatmap_panel(axes[sum_row][sum_col], summary_mat, title="Average across models", annot=True)

    # Hide unused axes
    for idx in range(n_panels, nrows * ncols):
        r, c = divmod(idx, ncols)
        axes[r][c].set_visible(False)

    plt.tight_layout()
    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    out_path = PLOTS_DIR / f"{col_label}_pvalue_heatmaps_{phase}.png"
    fig.savefig(out_path, dpi=600, bbox_inches="tight")
    plt.close(fig)
    print(f"  Saved: {out_path}")

    # Standalone summary figures (ttest only - one clean heatmap per phase/family)
    finetuned_mat = None
    if col_label == "ttest":
        import pandas as pd

        def _save_summary(mat: "pd.DataFrame", label: str) -> None:
            cell_size_sum = max(3.0, n_ft * 0.8)
            fig_dim = cell_size_sum * n_ft * 0.4 + 2
            fig_s, ax_s = plt.subplots(figsize=(fig_dim, fig_dim))
            _heatmap_panel(ax_s, mat, title="", annot=True)
            ax_s.set_title(
                f"Average P-Value\nPaired T-test ({metric.upper()}, {phase}, {label})",
                fontsize=17,
                fontweight="bold",
                pad=6,
            )
            path = PLOTS_DIR / f"ttest_pvalue_summary_{phase}_{label}.png"
            fig_s.savefig(path, dpi=600, bbox_inches="tight")
            plt.close(fig_s)
            print(f"  Saved: {path}")

        def _build_family_summary(model_list: list) -> "pd.DataFrame | None":
            if not model_list:
                return None
            arr = np.stack([model_matrices[m].values for m in model_list], axis=0).astype(float)
            diag = np.eye(n_ft, dtype=bool)
            arr[:, diag] = np.nan
            mean = np.nanmean(arr, axis=0)
            np.fill_diagonal(mean, 1.0)
            return pd.DataFrame(mean, index=all_fold_types, columns=all_fold_types)

        finetuned = [m for m in valid_models if not m.endswith("-gguf")]
        gguf = [m for m in valid_models if m.endswith("-gguf")]

        for family_label, model_list in [("finetuned", finetuned), ("gguf", gguf)]:
            mat = _build_family_summary(model_list)
            if mat is not None:
                _save_summary(mat, family_label)
                if family_label == "finetuned":
                    finetuned_mat = mat

    return finetuned_mat


# ─── Entry point ─────────────────────────────────────────────────────────────


def main() -> None:
    parser = ArgumentParser(description="P-value comparison heatmaps across fold types.")
    parser.add_argument("--results", type=Path, default=INDEX_RESULTS_FILE)
    parser.add_argument("--metric", type=str, default="f1", choices=METRICS)
    parser.add_argument("--phase", type=str, default="both", choices=["test", "holdout", "both"])
    parser.add_argument("--tag", type=str, default=None)
    parser.add_argument("--dataset", type=str, default=None)
    args = parser.parse_args()

    if not args.results.exists():
        print(f"ERROR: Results file not found: {args.results}")
        print("Run `uv run scripts/collect_results.py` first.")
        sys.exit(1)

    print(f"Loading results from {args.results} ...")
    df = load_results(args.results, tag=args.tag, dataset=args.dataset)

    sns.set_theme(style="whitegrid", context="paper")

    phases = PHASES if args.phase == "both" else [args.phase]
    finetuned_mats: dict[str, "pd.DataFrame"] = {}
    cached_metrics: dict[str, pl.DataFrame] = {}   # phase → collected metrics_df

    for phase in phases:
        print(f"\n{'=' * 60}")
        print(f"  Phase: {phase}")
        print(f"{'=' * 60}")

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            metrics_lf = prepare_per_fold_metrics(df, metric=args.metric, phase=phase)
            try:
                metrics_df = metrics_lf.collect(engine="streaming")
            except Exception:
                metrics_df = metrics_lf.collect()

        if metrics_df.is_empty():
            print(f"  No {phase} data. Skipping.")
            continue

        cached_metrics[phase] = metrics_df

        models = sorted(metrics_df["model"].unique().to_list())
        fold_types = sorted(metrics_df["fold_type"].unique().to_list())
        print(f"  Models: {', '.join(models)}")
        print(f"  Fold types: {', '.join(fold_types)}")

        for col_label, test_col in [("ttest", "P-Value"), ("wilcoxon", "Wilcoxon P-Value")]:
            mat = plot_pvalue_summary(metrics_df, phase, args.metric, test_col, col_label)
            if mat is not None and col_label == "ttest":
                finetuned_mats[phase] = mat

    # Generate LaTeX tables for ttest fine-tuned matrices
    PLOTS_DIR.mkdir(parents=True, exist_ok=True)
    for phase, mat in finetuned_mats.items():
        fold_types = sorted(mat.index.tolist())
        latex = _build_pvalue_latex_table(mat, fold_types, phase)
        out_path = PLOTS_DIR / f"pvalue_table_{phase}.tex"
        out_path.write_text(latex)
        print(f"  LaTeX p-value table → {out_path}")

    # ── TOST equivalence is now in scripts/plot_tost_grouped.py ───────────────
    # The cross-model TOST was replaced by per-(model, run_mode) paired TOST.
    # See docs/tost_grouped.md and run `uv run scripts/plot_tost_grouped.py`.

    # ── Superiority test (test phase only) ───────────────────────────────────
    print(f"\n{'=' * 60}")
    print("  Superiority Test (test set, H1: random > temporal)")
    print(f"{'=' * 60}")

    test_df = cached_metrics.get("test")
    if test_df is None:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            test_lf = prepare_per_fold_metrics(df, metric=args.metric, phase="test")
            try:
                test_df = test_lf.collect(engine="streaming")
            except Exception:
                test_df = test_lf.collect()

    if test_df is None or test_df.is_empty():
        print("  No test data. Skipping superiority test.")
    else:
        test_f1 = extract_mean_f1_matrix(test_df, metric=args.metric)
        all_test_models = sorted(test_f1.keys())
        ft_models      = [m for m in all_test_models if not m.endswith("-gguf")]
        gguf_t_models  = [m for m in all_test_models if m.endswith("-gguf")]

        for family_label, model_list in [("finetuned", ft_models), ("gguf", gguf_t_models)]:
            if not model_list:
                continue
            print(f"\n  Family: {family_label} ({len(model_list)} models: {', '.join(model_list)})")
            sup_results = run_superiority_pairs(test_f1, model_list)
            if not sup_results:
                print(f"  No superiority results for {family_label}.")
                continue
            for r in sup_results:
                sig_str = "SIG" if r["significant"] else "ns"
                print(
                    f"    {r['label']:30s}  d={r['mean_d']:+6.2f} pp  "
                    f"95% CI [{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}]  "
                    f"t={r['t_stat']:+.2f}  p_corr={_fmt_pvalue(r['p_corrected'])}  {sig_str}"
                )
            plot_superiority_forest(sup_results, family_label, metric=args.metric)
            write_superiority_latex_table(sup_results, family_label)

    # ── Intra-group comparison (random-vs-random, temporal-vs-temporal) ───────
    print(f"\n{'=' * 60}")
    print("  Intra-group Test (test set, within random / within temporal)")
    print(f"{'=' * 60}")

    if test_df is not None and not test_df.is_empty():
        test_f1 = extract_mean_f1_matrix(test_df, metric=args.metric)
        all_test_models = sorted(test_f1.keys())
        ft_models_ig   = [m for m in all_test_models if not m.endswith("-gguf")]
        gguf_t_models_ig = [m for m in all_test_models if m.endswith("-gguf")]

        for family_label, model_list in [("finetuned", ft_models_ig), ("gguf", gguf_t_models_ig)]:
            if not model_list:
                continue
            print(f"\n  Family: {family_label} ({len(model_list)} models: {', '.join(model_list)})")
            rand_results = run_intragroup_pairs(test_f1, model_list, RANDOM_PAIRS)
            temp_results = run_intragroup_pairs(test_f1, model_list, TEMPORAL_PAIRS)
            for r in rand_results + temp_results:
                sig_str = "SIG" if r["significant"] else "ns"
                equiv_str = "EQUIV" if r["equivalent"] else "not-equiv"
                print(
                    f"    {r['label']:30s}  d={r['mean_d']:+6.2f} pp  "
                    f"90% CI [{r['ci_lo']:+.2f}, {r['ci_hi']:+.2f}]  "
                    f"p_tost={_fmt_pvalue(r['p_tost'])} {equiv_str}  "
                    f"p_diff={_fmt_pvalue(r['p_corrected'])} {sig_str}"
                )
            write_intragroup_latex_table(rand_results, temp_results, family_label)

    print(f"\nAll outputs written to {PLOTS_DIR}")


if __name__ == "__main__":
    main()
