#!/usr/bin/env python
# PYTHON_ARGCOMPLETE_OK

"""
LaTeX table: test/holdout F1 inflation (%) for all models × all fold types.

Each cell shows (test_F1 / holdout_F1 − 1) × 100%, averaged across folds,
coloured red (inflation) / white (0) / green (deflation).

Usage:
    uv run scripts/table_all_models.py
    uv run scripts/table_all_models.py --tag my-tag --dataset megavul
"""
from __future__ import annotations

import sys
from argparse import ArgumentParser
from pathlib import Path
from typing import Optional

import polars as pl

try:
    from scripts import EDA_DIR, INDEX_RESULTS_FILE, PRIMARY_FOLD_TYPES
    from scripts.plot_results import compute_metrics, load_results, sort_models
except ModuleNotFoundError:
    sys.path.append(str(Path(__file__).resolve().parents[1]))
    from scripts import EDA_DIR, INDEX_RESULTS_FILE, PRIMARY_FOLD_TYPES
    from scripts.plot_results import compute_metrics, load_results, sort_models

# ─── Constants ────────────────────────────────────────────────────────────────

_FOLD_LABELS: dict[str, str] = {
    "k_fold_cross_validation":                 "K-Fold",
    "random_loo_block_cross_validation":        "Rand LOO",
    "random_growing_window_cross_validation":   "Rand GW",
    "temporal_loo_block_cross_validation":      "Temp LOO",
    "temporal_growing_window_cross_validation": "Temp GW",
}

# ─── Helpers ──────────────────────────────────────────────────────────────────


def _collect(lf: pl.LazyFrame) -> pl.DataFrame:
    try:
        return lf.collect(engine="streaming")
    except Exception:
        return lf.collect()


def _short(model: str) -> str:
    return model.replace("-gguf", "").replace("-", " ")


def _pct_cell(val: Optional[float], scale: float = 50.0) -> str:
    if val is None:
        return "---"
    t = max(-1.0, min(1.0, val / scale))
    if t < 0:
        r, g, b = 229, int(round(229 + t * (229 - 87))), int(round(229 + t * (229 - 87)))
    else:
        r, g, b = int(round(229 - t * (229 - 34))), int(round(229 + t * (139 - 229))), int(round(229 - t * (229 - 34)))
    return f"\\cellcolor[HTML]{{{r:02X}{g:02X}{b:02X}}} {val:+.1f}\\%"


# ─── Data ─────────────────────────────────────────────────────────────────────


def load_inflation(
    results_path: Path,
    tag: Optional[str],
    dataset: Optional[str],
) -> pl.DataFrame:
    """Return DataFrame with columns (model, fold_type, pct) = mean % inflation across folds."""
    group_cols = ["model", "run_mode", "fold_type", "fold_number"]

    lf = load_results(results_path, tag=tag, dataset=dataset)

    test_raw = compute_metrics(
        _collect(lf.filter(pl.col("phase") == "test")), group_cols
    )
    holdout_raw = compute_metrics(
        _collect(lf.filter(pl.col("phase") == "holdout")), group_cols
    )

    test_agg = test_raw.group_by(["model", "fold_type"]).agg(pl.col("f1").mean())
    holdout_agg = holdout_raw.group_by(["model", "fold_type"]).agg(pl.col("f1").mean().alias("f1_h"))

    joined = test_agg.join(holdout_agg, on=["model", "fold_type"], how="inner")
    joined = joined.with_columns(
        ((pl.col("f1") / pl.col("f1_h") - 1) * 100)
        .alias("pct")
    )
    return joined.select(["model", "fold_type", "pct"])


# ─── Table ────────────────────────────────────────────────────────────────────


def build_table(inflation: pl.DataFrame) -> str:
    all_models = sort_models(inflation["model"].unique().to_list())
    ft_models = [m for m in all_models if not m.endswith("-gguf")]
    zs_models = [m for m in all_models if m.endswith("-gguf")]
    n_ft, n_zs = len(ft_models), len(zs_models)
    n_data_cols = max(n_ft, n_zs)  # width determined by the wider group
    n_cols = 1 + n_data_cols

    lookup: dict[tuple[str, str], float] = {
        (row["model"], row["fold_type"]): row["pct"]
        for row in inflation.iter_rows(named=True)
    }

    col_spec = f"l *{{{n_data_cols}}}{{c}}"

    def _model_header(models: list[str]) -> str:
        cells = [f"\\rotatebox{{60}}{{\\footnotesize {_short(m)}}}" for m in models]
        # pad with empty cells if this group is narrower than n_data_cols
        cells += [""] * (n_data_cols - len(models))
        return f"    Fold Type & {' & '.join(cells)} \\\\"

    def _data_rows(models: list[str]) -> list[str]:
        rows = []
        for ft in PRIMARY_FOLD_TYPES:
            label = _FOLD_LABELS.get(ft, ft)
            cells = [_pct_cell(lookup.get((m, ft))) for m in models]
            cells += [""] * (n_data_cols - len(models))
            rows.append(f"    {label} & {' & '.join(cells)} \\\\")
        return rows

    lines: list[str] = [
        "% Auto-generated by scripts/table_all_models.py — do not edit manually.",
        "% Requires: \\usepackage{booktabs}, \\usepackage{colortbl}, \\usepackage{xcolor}",
        "\\begin{table}[htbp]",
        "  \\centering",
        "  \\footnotesize",
        f"  \\begin{{tabular}}{{{col_spec}}}",
        "    \\toprule",
        # Fine-tuning panel
        f"    \\multicolumn{{{n_cols}}}{{c}}{{\\textit{{Fine-tuning}}}} \\\\",
        "    \\midrule",
        _model_header(ft_models),
        "    \\midrule",
        *_data_rows(ft_models),
        "    \\midrule\\midrule",
        # Zero-shot panel
        f"    \\multicolumn{{{n_cols}}}{{c}}{{\\textit{{Zero-shot (OPRO)}}}} \\\\",
        "    \\midrule",
        _model_header(zs_models),
        "    \\midrule",
        *_data_rows(zs_models),
        "    \\bottomrule",
        "  \\end{tabular}",
        "  \\caption{Test/Holdout F1 inflation $(\\text{test}/\\text{holdout} - 1) \\times 100\\%$"
        " per model and fold type, averaged across folds."
        " Colour: red (test inflated above holdout) $\\to$ white (0) $\\to$ green (test below holdout).}",
        "  \\label{tab:all_models_overfit}",
        "\\end{table}",
    ]
    return "\n".join(lines) + "\n"


# ─── Main ─────────────────────────────────────────────────────────────────────


def main() -> None:
    parser = ArgumentParser(description="Write all-model test/holdout inflation LaTeX table.")
    parser.add_argument("--results", type=Path, default=INDEX_RESULTS_FILE)
    parser.add_argument("--tag", type=str, default=None)
    parser.add_argument("--dataset", type=str, default=None)
    parser.add_argument("--output", type=Path, default=EDA_DIR)
    args = parser.parse_args()

    print(f"Loading results from {args.results} …")
    inflation = load_inflation(args.results, args.tag, args.dataset)

    latex = build_table(inflation)

    args.output.mkdir(parents=True, exist_ok=True)
    out_path = args.output / "all_models_overfit.tex"
    out_path.write_text(latex)
    print(f"Saved → {out_path}")


if __name__ == "__main__":
    main()
